import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/legal/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — RevMate" },
      { name: "description", content: "How RevMate handles your data." },
      { property: "og:title", content: "Privacy Policy — RevMate" },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-10">
      <h1 className="text-2xl font-semibold tracking-tight">Privacy Policy</h1>
      <p className="mt-1 text-xs text-muted-foreground">Last updated 24 September 2026</p>

      <div className="mt-6 space-y-5 text-sm leading-relaxed text-muted-foreground">
        <section>
          <h2 className="mb-1 text-base font-semibold text-foreground">What we collect</h2>
          <p>
            Account details you provide (email, username), profile and garage content you choose
            to add (car details, photos, posts, comments), and activity generated by using the
            app (likes, dislikes, follows, messages, listings).
          </p>
        </section>

        <section>
          <h2 className="mb-1 text-base font-semibold text-foreground">How we use it</h2>
          <p>
            To operate the app's features — your feed, garage, marketplace listings, leaderboard
            ranks, and notifications — and to keep the community safe (moderation, blocking,
            reporting).
          </p>
        </section>

        <section>
          <h2 className="mb-1 text-base font-semibold text-foreground">What's public</h2>
          <p>
            Your username, garage cars, likes/dislikes/follower counts, public posts, and active
            marketplace listings are visible to other users and, where a page is public, to
            visitors who aren't signed in. Don't include personal contact or payment details in
            public listings or posts.
          </p>
        </section>

        <section>
          <h2 className="mb-1 text-base font-semibold text-foreground">Marketplace contact</h2>
          <p>
            RevMate does not currently provide in-app payments. If you exchange contact details
            with a buyer or seller to complete a sale, that exchange and any resulting
            conversation happens at your own discretion and risk.
          </p>
        </section>

        <section>
          <h2 className="mb-1 text-base font-semibold text-foreground">Your choices</h2>
          <p>
            You can edit or delete your garage cars, posts, and listings at any time. Contact us
            if you'd like your account and associated data deleted entirely.
          </p>
        </section>

        <p className="text-xs">
          This is a general placeholder policy and does not constitute legal advice. It should be
          reviewed by a solicitor for full UK GDPR compliance before wider launch.
        </p>
      </div>
    </div>
  );
}
