/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AskRouteImport } from './routes/ask'
import { Route as BattlesRouteImport } from './routes/battles'
import { Route as CommunityStandardsRouteImport } from './routes/community-standards'
import { Route as EssentialsRouteImport } from './routes/essentials'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NearYouRouteImport } from './routes/near-you'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RevsRouteImport } from './routes/revs'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as UpdatesDotjsonRouteImport } from './routes/updates[.]json'
import { Route as BusinessesIndexRouteImport } from './routes/businesses/index'
import { Route as BusinessesBusinessIdRouteImport } from './routes/businesses/$businessId'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsSlugRouteImport } from './routes/groups/$slug'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalSafetyRouteImport } from './routes/legal/safety'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalUpdatesRouteImport } from './routes/legal/updates'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace/$listingId'
import { Route as MeetsIndexRouteImport } from './routes/meets/index'
import { Route as MeetsMeetIdRouteImport } from './routes/meets/$meetId'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as TagsTagRouteImport } from './routes/tags.$tag'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as CarsMakeModelGenerationRouteImport } from './routes/cars/$make.$model.$generation'
import { Route as UUsernameCarsCarIdRouteImport } from './routes/u.$username_.cars.$carId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const BattlesRoute = BattlesRouteImport.update({
  id: '/battles',
  path: '/battles',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStandardsRoute = CommunityStandardsRouteImport.update({
  id: '/community-standards',
  path: '/community-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialsRoute = EssentialsRouteImport.update({
  id: '/essentials',
  path: '/essentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NearYouRoute = NearYouRouteImport.update({
  id: '/near-you',
  path: '/near-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RevsRoute = RevsRouteImport.update({
  id: '/revs',
  path: '/revs',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesDotjsonRoute = UpdatesDotjsonRouteImport.update({
  id: '/updates.json',
  path: '/updates.json',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/businesses/',
  path: '/businesses/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesBusinessIdRoute = BusinessesBusinessIdRouteImport.update({
  id: '/businesses/$businessId',
  path: '/businesses/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSafetyRoute = LegalSafetyRouteImport.update({
  id: '/legal/safety',
  path: '/legal/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalUpdatesRoute = LegalUpdatesRouteImport.update({
  id: '/legal/updates',
  path: '/legal/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/marketplace/$listingId',
  path: '/marketplace/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetsIndexRoute = MeetsIndexRouteImport.update({
  id: '/meets/',
  path: '/meets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetsMeetIdRoute = MeetsMeetIdRouteImport.update({
  id: '/meets/$meetId',
  path: '/meets/$meetId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MessagesRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagRoute = TagsTagRouteImport.update({
  id: '/tags/$tag',
  path: '/tags/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsMakeModelGenerationRoute = CarsMakeModelGenerationRouteImport.update({
  id: '/cars/$make/$model/$generation',
  path: '/cars/$make/$model/$generation',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameCarsCarIdRoute = UUsernameCarsCarIdRouteImport.update({
  id: '/u/$username_/cars/$carId',
  path: '/u/$username/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/battles': typeof BattlesRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/essentials': typeof EssentialsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/issues': typeof IssuesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/near-you': typeof NearYouRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revs': typeof RevsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates.json': typeof UpdatesDotjsonRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/updates': typeof LegalUpdatesRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/meets/$meetId': typeof MeetsMeetIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/u/$username': typeof UUsernameRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/meets/': typeof MeetsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/battles': typeof BattlesRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/essentials': typeof EssentialsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/issues': typeof IssuesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/near-you': typeof NearYouRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revs': typeof RevsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates.json': typeof UpdatesDotjsonRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/updates': typeof LegalUpdatesRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/meets/$meetId': typeof MeetsMeetIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/u/$username': typeof UUsernameRoute
  '/businesses': typeof BusinessesIndexRoute
  '/cars': typeof CarsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/meets': typeof MeetsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/ask': typeof AskRoute
  '/battles': typeof BattlesRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/essentials': typeof EssentialsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/issues': typeof IssuesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRouteWithChildren
  '/near-you': typeof NearYouRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revs': typeof RevsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/updates.json': typeof UpdatesDotjsonRoute
  '/businesses/$businessId': typeof BusinessesBusinessIdRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/updates': typeof LegalUpdatesRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/meets/$meetId': typeof MeetsMeetIdRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/tags/$tag': typeof TagsTagRoute
  '/u/$username': typeof UUsernameRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/cars/': typeof CarsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/meets/': typeof MeetsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username_/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/battles'
    | '/community-standards'
    | '/essentials'
    | '/forgot-password'
    | '/garage'
    | '/issues'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/near-you'
    | '/reset-password'
    | '/revs'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/updates.json'
    | '/businesses/$businessId'
    | '/groups/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/safety'
    | '/legal/terms'
    | '/legal/updates'
    | '/marketplace/$listingId'
    | '/meets/$meetId'
    | '/messages/$username'
    | '/posts/$postId'
    | '/tags/$tag'
    | '/u/$username'
    | '/businesses/'
    | '/cars/'
    | '/groups/'
    | '/marketplace/'
    | '/meets/'
    | '/cars/$make/$model/$generation'
    | '/u/$username/cars/$carId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/battles'
    | '/community-standards'
    | '/essentials'
    | '/forgot-password'
    | '/garage'
    | '/issues'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/near-you'
    | '/reset-password'
    | '/revs'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/updates.json'
    | '/businesses/$businessId'
    | '/groups/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/safety'
    | '/legal/terms'
    | '/legal/updates'
    | '/marketplace/$listingId'
    | '/meets/$meetId'
    | '/messages/$username'
    | '/posts/$postId'
    | '/tags/$tag'
    | '/u/$username'
    | '/businesses'
    | '/cars'
    | '/groups'
    | '/marketplace'
    | '/meets'
    | '/cars/$make/$model/$generation'
    | '/u/$username/cars/$carId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/ask'
    | '/battles'
    | '/community-standards'
    | '/essentials'
    | '/forgot-password'
    | '/garage'
    | '/issues'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/near-you'
    | '/reset-password'
    | '/revs'
    | '/robots.txt'
    | '/search'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/sitemap.xml'
    | '/updates.json'
    | '/businesses/$businessId'
    | '/groups/$slug'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/safety'
    | '/legal/terms'
    | '/legal/updates'
    | '/marketplace/$listingId'
    | '/meets/$meetId'
    | '/messages/$username'
    | '/posts/$postId'
    | '/tags/$tag'
    | '/u/$username'
    | '/businesses/'
    | '/cars/'
    | '/groups/'
    | '/marketplace/'
    | '/meets/'
    | '/cars/$make/$model/$generation'
    | '/u/$username_/cars/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AskRoute: typeof AskRoute
  BattlesRoute: typeof BattlesRoute
  CommunityStandardsRoute: typeof CommunityStandardsRoute
  EssentialsRoute: typeof EssentialsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GarageRoute: typeof GarageRoute
  IssuesRoute: typeof IssuesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  NearYouRoute: typeof NearYouRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevsRoute: typeof RevsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UpdatesDotjsonRoute: typeof UpdatesDotjsonRoute
  BusinessesBusinessIdRoute: typeof BusinessesBusinessIdRoute
  GroupsSlugRoute: typeof GroupsSlugRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSafetyRoute: typeof LegalSafetyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalUpdatesRoute: typeof LegalUpdatesRoute
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MeetsMeetIdRoute: typeof MeetsMeetIdRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  TagsTagRoute: typeof TagsTagRoute
  UUsernameRoute: typeof UUsernameRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
  CarsIndexRoute: typeof CarsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MeetsIndexRoute: typeof MeetsIndexRoute
  CarsMakeModelGenerationRoute: typeof CarsMakeModelGenerationRoute
  UUsernameCarsCarIdRoute: typeof UUsernameCarsCarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battles': {
      id: '/battles'
      path: '/battles'
      fullPath: '/battles'
      preLoaderRoute: typeof BattlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-standards': {
      id: '/community-standards'
      path: '/community-standards'
      fullPath: '/community-standards'
      preLoaderRoute: typeof CommunityStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essentials': {
      id: '/essentials'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof EssentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/near-you': {
      id: '/near-you'
      path: '/near-you'
      fullPath: '/near-you'
      preLoaderRoute: typeof NearYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revs': {
      id: '/revs'
      path: '/revs'
      fullPath: '/revs'
      preLoaderRoute: typeof RevsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates.json': {
      id: '/updates.json'
      path: '/updates.json'
      fullPath: '/updates.json'
      preLoaderRoute: typeof UpdatesDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/businesses'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses/$businessId': {
      id: '/businesses/$businessId'
      path: '/businesses/$businessId'
      fullPath: '/businesses/$businessId'
      preLoaderRoute: typeof BusinessesBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/safety': {
      id: '/legal/safety'
      path: '/legal/safety'
      fullPath: '/legal/safety'
      preLoaderRoute: typeof LegalSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/updates': {
      id: '/legal/updates'
      path: '/legal/updates'
      fullPath: '/legal/updates'
      preLoaderRoute: typeof LegalUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/marketplace/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meets/': {
      id: '/meets/'
      path: '/meets'
      fullPath: '/meets/'
      preLoaderRoute: typeof MeetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meets/$meetId': {
      id: '/meets/$meetId'
      path: '/meets/$meetId'
      fullPath: '/meets/$meetId'
      preLoaderRoute: typeof MeetsMeetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tag': {
      id: '/tags/$tag'
      path: '/tags/$tag'
      fullPath: '/tags/$tag'
      preLoaderRoute: typeof TagsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$make/$model/$generation': {
      id: '/cars/$make/$model/$generation'
      path: '/cars/$make/$model/$generation'
      fullPath: '/cars/$make/$model/$generation'
      preLoaderRoute: typeof CarsMakeModelGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/cars/$carId': {
      id: '/u/$username_/cars/$carId'
      path: '/u/$username/cars/$carId'
      fullPath: '/u/$username/cars/$carId'
      preLoaderRoute: typeof UUsernameCarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesUsernameRoute: typeof MessagesUsernameRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesUsernameRoute: MessagesUsernameRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AskRoute: AskRoute,
  BattlesRoute: BattlesRoute,
  CommunityStandardsRoute: CommunityStandardsRoute,
  EssentialsRoute: EssentialsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GarageRoute: GarageRoute,
  IssuesRoute: IssuesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRouteWithChildren,
  NearYouRoute: NearYouRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevsRoute: RevsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UpdatesDotjsonRoute: UpdatesDotjsonRoute,
  BusinessesBusinessIdRoute: BusinessesBusinessIdRoute,
  GroupsSlugRoute: GroupsSlugRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSafetyRoute: LegalSafetyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalUpdatesRoute: LegalUpdatesRoute,
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MeetsMeetIdRoute: MeetsMeetIdRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  TagsTagRoute: TagsTagRoute,
  UUsernameRoute: UUsernameRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
  CarsIndexRoute: CarsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MeetsIndexRoute: MeetsIndexRoute,
  CarsMakeModelGenerationRoute: CarsMakeModelGenerationRoute,
  UUsernameCarsCarIdRoute: UUsernameCarsCarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
