/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CommunityStandardsRouteImport } from './routes/community-standards'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CarsIndexRouteImport } from './routes/cars/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsSlugRouteImport } from './routes/groups/$slug'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as MessagesUsernameRouteImport } from './routes/messages.$username'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as CarsMakeModelGenerationRouteImport } from './routes/cars/$make.$model.$generation'
import { Route as UUsernameCarsCarIdRouteImport } from './routes/u.$username_.cars.$carId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityStandardsRoute = CommunityStandardsRouteImport.update({
  id: '/community-standards',
  path: '/community-standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsIndexRoute = CarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/groups/$slug',
  path: '/groups/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUsernameRoute = MessagesUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => MessagesRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsMakeModelGenerationRoute = CarsMakeModelGenerationRouteImport.update({
  id: '/cars/$make/$model/$generation',
  path: '/cars/$make/$model/$generation',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameCarsCarIdRoute = UUsernameCarsCarIdRouteImport.update({
  id: '/u/$username_/cars/$carId',
  path: '/u/$username/cars/$carId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/cars/': typeof CarsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/cars': typeof CarsIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/community-standards': typeof CommunityStandardsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/garage': typeof GarageRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/messages': typeof MessagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/messages/$username': typeof MessagesUsernameRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/cars/': typeof CarsIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/cars/$make/$model/$generation': typeof CarsMakeModelGenerationRoute
  '/u/$username_/cars/$carId': typeof UUsernameCarsCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask'
    | '/community-standards'
    | '/forgot-password'
    | '/garage'
    | '/leaderboard'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/groups/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/messages/$username'
    | '/posts/$postId'
    | '/u/$username'
    | '/cars/'
    | '/groups/'
    | '/cars/$make/$model/$generation'
    | '/u/$username/cars/$carId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ask'
    | '/community-standards'
    | '/forgot-password'
    | '/garage'
    | '/leaderboard'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/groups/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/messages/$username'
    | '/posts/$postId'
    | '/u/$username'
    | '/cars'
    | '/groups'
    | '/cars/$make/$model/$generation'
    | '/u/$username/cars/$carId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask'
    | '/community-standards'
    | '/forgot-password'
    | '/garage'
    | '/leaderboard'
    | '/login'
    | '/marketplace'
    | '/messages'
    | '/reset-password'
    | '/sell'
    | '/settings'
    | '/signup'
    | '/groups/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/messages/$username'
    | '/posts/$postId'
    | '/u/$username'
    | '/cars/'
    | '/groups/'
    | '/cars/$make/$model/$generation'
    | '/u/$username_/cars/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AskRoute: typeof AskRoute
  CommunityStandardsRoute: typeof CommunityStandardsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GarageRoute: typeof GarageRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MessagesRoute: typeof MessagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  GroupsSlugRoute: typeof GroupsSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  CarsIndexRoute: typeof CarsIndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  CarsMakeModelGenerationRoute: typeof CarsMakeModelGenerationRoute
  UUsernameCarsCarIdRoute: typeof UUsernameCarsCarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-standards': {
      id: '/community-standards'
      path: '/community-standards'
      fullPath: '/community-standards'
      preLoaderRoute: typeof CommunityStandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/': {
      id: '/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof CarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/groups/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$username': {
      id: '/messages/$username'
      path: '/$username'
      fullPath: '/messages/$username'
      preLoaderRoute: typeof MessagesUsernameRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$make/$model/$generation': {
      id: '/cars/$make/$model/$generation'
      path: '/cars/$make/$model/$generation'
      fullPath: '/cars/$make/$model/$generation'
      preLoaderRoute: typeof CarsMakeModelGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username_/cars/$carId': {
      id: '/u/$username_/cars/$carId'
      path: '/u/$username/cars/$carId'
      fullPath: '/u/$username/cars/$carId'
      preLoaderRoute: typeof UUsernameCarsCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MessagesRouteChildren {
  MessagesUsernameRoute: typeof MessagesUsernameRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesUsernameRoute: MessagesUsernameRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AskRoute: AskRoute,
  CommunityStandardsRoute: CommunityStandardsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GarageRoute: GarageRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MessagesRoute: MessagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  GroupsSlugRoute: GroupsSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  UUsernameRoute: UUsernameRoute,
  CarsIndexRoute: CarsIndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  CarsMakeModelGenerationRoute: CarsMakeModelGenerationRoute,
  UUsernameCarsCarIdRoute: UUsernameCarsCarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
